import { calculateHealthScore } from "./projectHealth.js";
import type { HealthCheckResult } from "./projectHealth.js";
import type { ProjectScanResult } from "./readProject.js";

const TODO_FIXME_HEADING = `### ${"TODO"}/FIXME Items`;

type ReportResult = ProjectScanResult & {
  source?: {
    type: "local" | "github";
    label: string;
    repositoryUrl?: string;
  };
};

function escapeTableCell(value: string) {
  return value.split("|").join("\\|").replace(/\r?\n/g, " ");
}

function formatInlineCode(value: string) {
  return `\`${value.split("`").join("\\`")}\``;
}

function formatStatus(found: boolean) {
  return found ? "Found" : "Missing";
}

function formatCheckRows(checks: HealthCheckResult[]) {
  return checks.map(
    (check) => `| ${escapeTableCell(check.name)} | ${formatStatus(check.found)} |`,
  );
}

export function formatJsonReport(result: ReportResult) {
  return JSON.stringify(result, null, 2);
}

export function formatMarkdownReport(result: ReportResult) {
  const healthScore = calculateHealthScore(result.projectHealth);
  const repositoryUrl = result.source?.type === "github" ? result.source.repositoryUrl : undefined;
  const isGitHubReport = Boolean(repositoryUrl);
  const sourceLabel = result.source?.label ?? "Local folder";
  const lines: string[] = [
    "# RepoLens Report",
    "",
    "> Repository health report generated by RepoLens.",
    "",
    "## Overview",
    "",
    "| Metric | Value |",
    "|---|---:|",
    ...(repositoryUrl
      ? [`| Repository | ${formatInlineCode(repositoryUrl)} |`]
      : [`| Project | ${formatInlineCode(result.projectPath)} |`]),
    `| Source | ${sourceLabel} |`,
    `| Health Score | **${healthScore.score}%** |`,
    `| Files | ${result.totalFiles} |`,
    `| Folders | ${result.totalFolders} |`,
    `| Lines of Code | ${result.totalLines} |`,
    ...(isGitHubReport ? ["", "> Analyzed from a temporary local clone."] : []),
    "",
    "## Configuration",
    "",
    "| File | Status |",
    "|---|---|",
    `| ${result.config.configFileName} | ${
      result.config.configFileFound ? "Found" : "Not found, using defaults"
    } |`,
    "",
    "## Language Breakdown",
    "",
    "| Language | Files |",
    "|---|---:|",
  ];

  if (result.languageBreakdown.length === 0) {
    lines.push("| No files detected | 0 |");
  } else {
    lines.push(
      ...result.languageBreakdown.map(
        (item) => `| ${escapeTableCell(item.language)} | ${item.files} |`,
      ),
    );
  }

  lines.push("", "## Detected Stack", "");
  if (result.detectedStack.length === 0) {
    lines.push("- No known technologies detected");
  } else {
    lines.push(...result.detectedStack.map((technology) => `- ${escapeTableCell(technology)}`));
  }

  lines.push(
    "",
    "## Project Structure",
    "",
    "```txt",
    ...result.projectStructure,
    "```",
  );

  lines.push(
    "",
    "## Code Quality",
    "",
    "| Check | Result |",
    "|---|---:|",
    `| TODO/FIXME Comments | ${result.todos.length} |`,
    `| Large Files Over ${result.config.config.largeFileThreshold} Lines | ${result.largeFiles.length} |`,
  );

  if (result.todos.length > 0) {
    lines.push(
      "",
      TODO_FIXME_HEADING,
      "",
      "| File | Line | Comment |",
      "|---|---:|---|",
      ...result.todos.slice(0, 10).map((todo) => {
        return `| ${formatInlineCode(todo.filePath)} | ${todo.lineNumber} | ${escapeTableCell(
          todo.text,
        )} |`;
      }),
    );
  }

  if (result.largeFiles.length > 0) {
    lines.push(
      "",
      "### Large Files",
      "",
      "| File | Lines |",
      "|---|---:|",
      ...result.largeFiles
        .slice(0, 10)
        .map((file) => `| ${formatInlineCode(file.filePath)} | ${file.lineCount} |`),
    );
  }

  lines.push(
    "",
    "## Project Health",
    "",
    "| Check | Status |",
    "|---|---|",
    ...formatCheckRows(result.projectHealth.importantFiles),
    "",
    "## README Quality",
    "",
    "| Check | Status |",
    "|---|---|",
  );

  if (result.projectHealth.readmeQuality.length === 0) {
    lines.push("| README.md | Missing |");
  } else {
    lines.push(...formatCheckRows(result.projectHealth.readmeQuality));
  }

  lines.push(
    "",
    "## .gitignore Checks",
    "",
    "| Entry | Status |",
    "|---|---|",
    ...formatCheckRows(result.projectHealth.gitignoreChecks),
    "",
    "## package.json Metadata",
    "",
    "| Field | Status |",
    "|---|---|",
    ...formatCheckRows(result.projectHealth.packageJsonMetadata),
    "",
    "## Notes",
    "",
    "Generated with RepoLens.",
  );

  return `${lines.join("\n")}\n`;
}
